{
 "title": "GitHub Pull Request Statistics",
 "time": { "from": "2023-10-05T22:07:58.000Z", "to": "2023-10-27T23:32:05.000Z" },
 "templating": {
  "list": [
   {
    "name": "repository_name",
    "query": "tensorflow, freeCodeCamp, bovem.github.io, mermaid"
   },
   { "name": "DS_POSTGRESQL", "query": "PostgreSQL" }
  ]
 },
 "panels": [
  {
   "title": "Number of Pull Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(pr_url) FROM \"${repository_name}_pr_data\" GROUP BY pr_url "
    }
   ]
  },
  {
   "title": "Number of PR Creators",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(pr_creator) FROM \"${repository_name}_pr_data\" WHERE COALESCE(pr_creator, '') <> '' GROUP BY pr_creator "
    }
   ]
  },
  {
   "title": "States of Pull Requests (Open/Close)",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(pr_state), pr_state FROM \"${repository_name}_pr_data\" GROUP BY pr_state"
    }
   ]
  },
  {
   "title": "Merge Status of Closed Pull Requests",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT pr_merge, COUNT(pr_url) FROM \"${repository_name}_pr_data\" WHERE pr_state = 'Closed' GROUP BY pr_merge LIMIT 50 "
    }
   ]
  },
  {
   "title": "Last Merged PR",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT pr_merging_time, pr_title FROM \"${repository_name}_pr_data\" WHERE pr_merging_time IS NOT NULL ORDER BY pr_merging_time DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "Last Closed PR",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT pr_closing_time, pr_title FROM \"${repository_name}_pr_data\" WHERE pr_closing_time IS NOT NULL ORDER BY pr_closing_time DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "Average Creation to Closing Duration",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(time_delta_closing_creation) FROM \"${repository_name}_pr_data\" LIMIT 50 "
    }
   ]
  },
  {
   "title": "Average Creation to Merging Duration",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(time_delta_merging_creation) FROM \"${repository_name}_pr_data\" LIMIT 50 "
    }
   ]
  },
  {
   "title": "Duration of last closed PR",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time_delta_closing_creation, pr_closing_time FROM \"${repository_name}_pr_data\" ORDER BY pr_closing_time LIMIT 1 "
    }
   ]
  },
  {
   "title": "Last 5 Closed Pull Requests",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT pr_closing_time AS \"PR Closing Time\", pr_title AS \"PR Title\", pr_merge AS \"Merged PR\", pr_url AS \"PR URL\", time_delta_closing_creation AS \"Time Delta between PR Creation and Closing\" FROM \"${repository_name}_pr_data\" WHERE pr_closing_time IS NOT NULL ORDER BY pr_closing_time DESC LIMIT 5 "
    }
   ]
  },
  {
   "title": "Pull Request Timeline",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "rawSql": "SELECT pr_creation_time, pr_number FROM \"${repository_name}_pr_data\" ORDER BY pr_creation_time DESC "
    }
   ]
  },
  {
   "title": "Top 10 PR Creators",
   "type": "barchart",
   "gridPos": { "h": 14, "w": 13, "x": 0, "y": 33 },
   "targets": [
    {
     "rawSql": "SELECT pr_creator, COUNT(pr_url) FROM \"${repository_name}_pr_data\" GROUP BY pr_creator ORDER BY COUNT(pr_url) DESC LIMIT 10 "
    }
   ]
  },
  {
   "title": "PR Creators",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 11, "x": 13, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT pr_creator, COUNT(pr_url) FROM \"${repository_name}_pr_data\" GROUP BY pr_creator ORDER BY COUNT(pr_url) DESC "
    }
   ]
  }
 ]
}