{
 "title": "Pull Request and PipelineRun Statistics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "repository_name",
    "query": "certified-operators, certified-operators-preprod, redhat-marketplace-operators, redhat-marketplace-operators-preprod"
   },
   { "name": "DS_POSTGRESQL", "query": "PostgreSQL" }
  ]
 },
 "panels": [
  {
   "title": "Last Hosted PipelineRun Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT pipelinerun_start_time, pipelinerun_status, pipelinerun FROM \"${repository_name}_pr_comments_stats\" WHERE (COALESCE(pipelinerun, '') <> '' AND pipeline_name = 'operator-hosted-pipeline') ORDER BY pipelinerun_start_time DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "Last Release PipelineRun Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT pipelinerun_start_time, pipelinerun_status, pipelinerun FROM \"${repository_name}_pr_comments_stats\" WHERE (COALESCE(pipelinerun, '') <> '' AND pipeline_name = 'operator-release-pipeline') ORDER BY pipelinerun_start_time DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "Last 5 Hosted PipelineRuns",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT pipelinerun_start_time, pipelinerun_status, pipelinerun, pr_url, pipelinerun_duration FROM \"${repository_name}_pr_comments_stats\" WHERE (COALESCE(pipelinerun, '') <> '' AND pipeline_name = 'operator-hosted-pipeline') ORDER BY pipelinerun_start_time DESC LIMIT 5 "
    }
   ]
  },
  {
   "title": "Last 5 Release PipelineRuns",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT pipelinerun_start_time, pipelinerun_status, pipelinerun, pr_url, pipelinerun_duration FROM \"${repository_name}_pr_comments_stats\" WHERE (COALESCE(pipelinerun, '') <> '' AND pipeline_name = 'operator-release-pipeline') ORDER BY pipelinerun_start_time DESC LIMIT 5 "
    }
   ]
  },
  { "title": "Pull Request Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Number of Operators",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT operator_name FROM \"${repository_name}_pr_data\" WHERE COALESCE(operator_name, '') <> '' GROUP BY operator_name "
    }
   ]
  },
  {
   "title": "Number of PR Creators",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT pr_creator FROM \"${repository_name}_pr_data\" WHERE COALESCE(pr_creator, '') <> '' GROUP BY pr_creator "
    }
   ]
  },
  {
   "title": "Last Closed PR",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT pr_closing_time, pr_title FROM \"${repository_name}_pr_data\" WHERE pr_closing_time IS NOT NULL ORDER BY pr_closing_time DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "Last Merged PR",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT pr_merging_time, pr_title FROM \"${repository_name}_pr_data\" WHERE pr_merging_time IS NOT NULL ORDER BY pr_merging_time DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "Duration of last closed PR",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time_delta_closing_creation, pr_closing_time FROM \"${repository_name}_pr_data\" ORDER BY pr_closing_time LIMIT 1 "
    }
   ]
  },
  {
   "title": "Average Creation to Merging Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 9, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(time_delta_merging_creation) FROM \"${repository_name}_pr_data\" LIMIT 50 "
    }
   ]
  },
  {
   "title": "Average Creation to Closing Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(time_delta_closing_creation) FROM \"${repository_name}_pr_data\" LIMIT 50 "
    }
   ]
  },
  {
   "title": "Last 5 Closed PRs",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT pr_closing_time, pr_title, pr_merge, pr_url, time_delta_closing_creation FROM \"${repository_name}_pr_data\" WHERE pr_closing_time IS NOT NULL ORDER BY pr_closing_time DESC LIMIT 5 "
    }
   ]
  },
  {
   "title": "Top 10 PR Creators",
   "type": "barchart",
   "gridPos": { "h": 14, "w": 13, "x": 0, "y": 33 },
   "targets": [
    {
     "rawSql": "SELECT pr_creator, COUNT(pr_url) FROM \"${repository_name}_pr_data\" GROUP BY pr_creator ORDER BY COUNT(pr_url) DESC LIMIT 10 "
    }
   ]
  },
  {
   "title": "PR Creators",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 11, "x": 13, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT pr_creator, COUNT(pr_url) FROM \"${repository_name}_pr_data\" GROUP BY pr_creator ORDER BY COUNT(pr_url) DESC "
    }
   ]
  },
  {
   "title": "Top 10 Operators by PR",
   "type": "barchart",
   "gridPos": { "h": 14, "w": 13, "x": 0, "y": 47 },
   "targets": [
    {
     "rawSql": "SELECT operator_name, COUNT(pr_url) FROM \"${repository_name}_pr_data\" WHERE COALESCE(operator_name, '') <> '' GROUP BY operator_name ORDER BY COUNT(pr_url) DESC LIMIT 10 "
    }
   ]
  },
  {
   "title": "PR composition by Operators",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 11, "x": 13, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT operator_name, COUNT(pr_url) FROM \"${repository_name}_pr_data\" WHERE COALESCE(operator_name, '') <> '' GROUP BY operator_name ORDER BY COUNT(pr_url) DESC "
    }
   ]
  },
  { "title": "PipelineRun Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Number of Hosted PipelineRuns",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(pipelinerun) FROM \"${repository_name}_pr_comments_stats\" WHERE pipeline_name = 'operator-hosted-pipeline' GROUP BY pipelinerun "
    }
   ]
  },
  {
   "title": "Average Hosted Pipeline Duration (Last 5)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT MAX(pipelinerun_duration), pipelinerun_start_time FROM \"${repository_name}_pr_comments_stats\" WHERE pipeline_name = 'operator-hosted-pipeline' GROUP BY pipelinerun_start_time, pipelinerun ORDER BY pipelinerun_start_time DESC LIMIT 5 "
    }
   ]
  },
  {
   "title": "Number of ReleasePipelineRuns",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(pipelinerun) FROM \"${repository_name}_pr_comments_stats\" WHERE pipeline_name = 'operator-release-pipeline' GROUP BY pipelinerun "
    }
   ]
  },
  {
   "title": "Average Release Pipeline Duration (Last 5)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT MAX(pipelinerun_duration), pipelinerun_start_time FROM \"${repository_name}_pr_comments_stats\" WHERE pipeline_name = 'operator-release-pipeline' GROUP BY pipelinerun_start_time, pipelinerun ORDER BY pipelinerun_start_time DESC LIMIT 5 "
    }
   ]
  },
  {
   "title": "Average Hosted Pipeline Duration (All Time)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT MAX(pipelinerun_duration), pipeline_name FROM \"${repository_name}_pr_comments_stats\" WHERE pipeline_name = 'operator-hosted-pipeline' GROUP BY pipelinerun, pipeline_name "
    }
   ]
  },
  {
   "title": "Average Release Pipeline Duration (All Time)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT MAX(pipelinerun_duration), pipeline_name FROM \"${repository_name}_pr_comments_stats\" WHERE pipeline_name = 'operator-release-pipeline' GROUP BY pipelinerun, pipeline_name "
    }
   ]
  },
  {
   "title": "Average Hosted Pipeline Duration (All Time)",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT MAX(pipelinerun_duration) FROM \"${repository_name}_pr_comments_stats\" WHERE pipeline_name = 'operator-hosted-pipeline' GROUP BY pipelinerun "
    }
   ]
  },
  {
   "title": "Average Release Pipeline Duration (All Time)",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT pipelinerun_duration, pipelinerun FROM \"${repository_name}_pr_comments_stats\" WHERE pipeline_name = 'operator-release-pipeline' "
    }
   ]
  },
  {
   "title": "Average preflight-trigger Duration (All Time)",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT taskrun_duration FROM \"${repository_name}_pr_comments_stats\" WHERE taskrun = 'preflight-trigger' ORDER BY pipelinerun_start_time DESC "
    }
   ]
  },
  {
   "title": "Average request-signature Duration (All Time)",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT taskrun_duration FROM \"${repository_name}_pr_comments_stats\" WHERE taskrun = 'request-signature' ORDER BY pipelinerun_start_time DESC "
    }
   ]
  },
  {
   "title": "Average TaskRun Duration (Operator Hosted Pipeline)",
   "type": "table",
   "gridPos": { "h": 40, "w": 12, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT taskrun, AVG(taskrun_duration) FROM \"${repository_name}_pr_comments_stats\" WHERE (pipelinerun_comment = true AND COALESCE(taskrun, '') <> '' AND pipeline_name = 'operator-hosted-pipeline') GROUP BY taskrun ORDER BY AVG(taskrun_duration) DESC LIMIT 50 "
    }
   ]
  },
  {
   "title": "Average TaskRun Duration (Operator Release Pipeline)",
   "type": "table",
   "gridPos": { "h": 21, "w": 12, "x": 12, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT taskrun, AVG(taskrun_duration) FROM \"${repository_name}_pr_comments_stats\" WHERE (pipelinerun_comment = true AND COALESCE(taskrun, '') <> '' AND pipeline_name = 'operator-release-pipeline') GROUP BY taskrun ORDER BY AVG(taskrun_duration) DESC LIMIT 50 "
    }
   ]
  }
 ]
}